name: MavCrop
author: dustin
category: Interface
tags: [crop, image, UI, GUI]
demo: http://maveno.us/library/public/mavcrop/
docs: http://maveno.us/library/public/mavcrop/
mooshell: http://maveno.us/library/public/mavcrop/
current: 0.6